local GAME_SCREEN_DATA = { VARS = {} }

GAME_SCREEN_DATA['Installing_the_screen'] = function()
 GAME_SCREEN_DATA.VARS.CENTER_X = display.contentCenterX
 GAME_SCREEN_DATA.VARS.CENTER_Y = display.contentCenterY
 GAME_SCREEN_DATA.VARS.SCREEN_WIDTH = display.actualContentWidth
 GAME_SCREEN_DATA.VARS.SCREEN_HEIGHT = display.actualContentHeight
 GAME_SCREEN_DATA.VARS.TOP_HEIGHT, GAME_SCREEN_DATA.VARS.LEFT_HEIGHT, GAME_SCREEN_DATA.VARS.BOTTOM_HEIGHT, GAME_SCREEN_DATA.VARS.RIGHT_HEIGHT = display.getSafeAreaInsets()
 GAME_SCREEN_DATA.VARS.ZERO_X = GAME_SCREEN_DATA.VARS.CENTER_X - GAME_SCREEN_DATA.VARS.SCREEN_WIDTH / 2 + GAME_SCREEN_DATA.VARS.LEFT_HEIGHT
 GAME_SCREEN_DATA.VARS.ZERO_Y = GAME_SCREEN_DATA.VARS.CENTER_Y - GAME_SCREEN_DATA.VARS.SCREEN_HEIGHT / 2 + GAME_SCREEN_DATA.VARS.TOP_HEIGHT
 GAME_SCREEN_DATA.VARS.MAX_X = GAME_SCREEN_DATA.VARS.CENTER_X + GAME_SCREEN_DATA.VARS.SCREEN_WIDTH / 2 - GAME_SCREEN_DATA.VARS.RIGHT_HEIGHT
 GAME_SCREEN_DATA.VARS.MAX_Y = GAME_SCREEN_DATA.VARS.CENTER_Y + GAME_SCREEN_DATA.VARS.SCREEN_HEIGHT / 2 - GAME_SCREEN_DATA.VARS.BOTTOM_HEIGHT
end

GAME_SCREEN_DATA['Delete'] = function()
 for key in pairs(GAME_SCREEN_DATA.VARS) do
  GAME_SCREEN_DATA.VARS[key] = 0
 end
end

return GAME_SCREEN_DATA